services:
  telegram-ai-bot:
    build: .
    container_name: telegram-ai-bot
    volumes:
      - ./data:/app/data
    environment:
      - API_ID=YOUR_API_ID
      - API_HASH=YOUR_API_HASH
      - AI_API_KEY=YOUR_AI_API_KEY
      - TARGET_USER=YOUR_TARGET_USER
    restart: unless-stopped
