services:
  telegram-ai-bot:
    build: .
    container_name: telegram-ai-bot
    environment:
      - API_ID=YOUR_API_ID
      - API_HASH=YOUR_API_HASH
      - AI_API_KEY=YOUR_AI_API_KEY
    restart: unless-stopped
